// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMwwtxxZHt4wGGGd0NCImXGd574T3qVNE',
    appId: '1:379448828965:web:267d566cd0cfcbbd27cbcc',
    messagingSenderId: '379448828965',
    projectId: 'nado-giza',
    authDomain: 'nado-giza.firebaseapp.com',
    storageBucket: 'nado-giza.appspot.com',
    measurementId: 'G-EH37W55BFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq46o0UNZ6smpX6DiLy8wW24JUTFcMK1E',
    appId: '1:379448828965:android:19266a0f95bca1a627cbcc',
    messagingSenderId: '379448828965',
    projectId: 'nado-giza',
    storageBucket: 'nado-giza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuOmPpCisKDk-llq2Ka4K7NIkBzcXIznk',
    appId: '1:379448828965:ios:5fc511c03386cb8627cbcc',
    messagingSenderId: '379448828965',
    projectId: 'nado-giza',
    storageBucket: 'nado-giza.appspot.com',
    iosClientId: '379448828965-h7g0jgredg8og9if26cnc7vnvouhdnto.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadoGiza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuOmPpCisKDk-llq2Ka4K7NIkBzcXIznk',
    appId: '1:379448828965:ios:0f6714ffe88bb73f27cbcc',
    messagingSenderId: '379448828965',
    projectId: 'nado-giza',
    storageBucket: 'nado-giza.appspot.com',
    iosClientId: '379448828965-gcmjssdukt6jdnnhrfhsk080pn3cbc3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadoGiza.RunnerTests',
  );
}
